CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uid VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  father VARCHAR(255) NOT NULL,
  mother VARCHAR(255) NOT NULL,
  contact VARCHAR(20) NOT NULL,
  birthday DATE NOT NULL,
  education VARCHAR(255) NOT NULL,
  cgpa DECIMAL(3,2) NOT NULL,
  interest VARCHAR(255) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  trxid VARCHAR(255) NOT NULL,
  photo VARCHAR(255) DEFAULT 'default.png',
  status ENUM('completed', 'rejected', 'pending') NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);